AplicatieMDS/Controllers/ChatsController.cs
using AplicatieMDS.Data;
using AplicatieMDS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace AplicatieMDS.Controllers
{
    public class ChatsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;

        public ChatsController(ApplicationDbContext context, UserManager<ApplicationUser> userManager)
        {
            db = context;
            _userManager = userManager;
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> Index()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return Redirect("/Identity/Account/Login");
            }

            // Load chats
            var chats = await db.Chats
                .Include(c => c.CurrentUser)
                .Include(c => c.FriendUser)
                .Where(c => c.CurrentUserId == userId || c.FriendUserId == userId)
                .ToListAsync();

            ViewBag.UserCurent = userId;
            return View(chats);
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> Show(int id)
        {
            var chat = await db.Chats
                .Include(c => c.CurrentUser)
                .Include(c => c.FriendUser)
                .Include(c => c.Messages)
                .ThenInclude(m => m.User)
                .FirstOrDefaultAsync(c => c.Id == id);

            if (chat == null)
            {
                TempData["message"] = "Acest chat nu a fost găsit!";
                TempData["messageType"] = "alert-danger";
                return RedirectToAction("Index");
            }

            var chatUserList = await db.ChatUsers.Where(ch => ch.ChatId == id).ToListAsync();
            SetAccessRights();

            if (User.IsInRole("Admin") || User.IsInRole("Moderator") || chatUserList.Any(cu => cu.UserId == _userManager.GetUserId(User)))
            {
                return View(chat);
            }

            TempData["message"] = "Nu aveți drepturi pentru a vizualiza acest canal!";
            TempData["messageType"] = "alert-danger";
            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> Show([FromForm] Message message)
        {
            message.Date = DateTime.Now;
            message.UserId = _userManager.GetUserId(User);

            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                await db.SaveChangesAsync();

                if (Request.Headers["X-Requested-With"] == "XMLHttpRequest")
                {
                    var chatMessages = db.Messages.Where(m => m.ChatId == message.ChatId).Include(m => m.User).ToList();
                    return PartialView("_MessagesPartial", chatMessages);
                }

                return RedirectToAction("Show", new { id = message.ChatId });
            }

            var chat = await db.Chats
                .Include(c => c.CurrentUser)
                .Include(c => c.FriendUser)
                .Include(c => c.Messages)
                .ThenInclude(m => m.User)
                .FirstOrDefaultAsync(c => c.Id == message.ChatId);

            SetAccessRights();
            return View(chat);
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> GetOrCreateChat(string friendId)
        {
            var currentUserId = _userManager.GetUserId(User);

            // Check if a chat already exists between the current user and the friend
            var existingChat = await db.Chats
                .FirstOrDefaultAsync(c => (c.CurrentUserId == currentUserId && c.FriendUserId == friendId) ||
                                          (c.CurrentUserId == friendId && c.FriendUserId == currentUserId));

            if (existingChat != null)
            {
                // Chat already exists, load messages
                return PartialView("_MessagesPartial", existingChat.Messages);
            }

            // Create a new chat if it doesn't exist
            var chat = new Chat
            {
                CurrentUserId = currentUserId,
                FriendUserId = friendId
            };

            if (ModelState.IsValid)
            {
                db.Chats.Add(chat);
                await db.SaveChangesAsync();

                var chatUser = new ChatUser
                {
                    ChatId = chat.Id,
                    UserId = chat.CurrentUserId
                };

                db.ChatUsers.Add(chatUser);
                await db.SaveChangesAsync();

                TempData["message"] = "The chat has been created";
                TempData["messageType"] = "alert-success";
                return PartialView("_MessagesPartial", chat.Messages);
            }

            TempData["message"] = "Failed to create the chat";
            TempData["messageType"] = "alert-danger";
            return RedirectToAction("ShowAllFriends", "Users");
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> MarkAsSeen(int chatId)
        {
            var userId = _userManager.GetUserId(User);
            var chat = await db.Chats.Include(c => c.Messages)
                                      .FirstOrDefaultAsync(c => c.Id == chatId && (c.CurrentUserId == userId || c.FriendUserId == userId));

            if (chat == null)
            {
                return NotFound();
            }

            var unseenMessages = chat.Messages.Where(m => m.UserId != userId && m.Status == Message.MessageStatus.Unseen).ToList();
            foreach (var message in unseenMessages)
            {
                message.Status = Message.MessageStatus.Seen;
            }

            await db.SaveChangesAsync();

            return Ok();
        }



        private void SetAccessRights()
        {
            ViewBag.EsteAdmin = User.IsInRole("Admin");
            ViewBag.EsteModerator = User.IsInRole("Moderator");
            ViewBag.UserCurent = _userManager.GetUserId(User);
            ViewBag.UserNameCurent = _userManager.GetUserName(User);
        }
    }
}

AplicatieMDS/Controllers/UsersController.cs
using AplicatieMDS.Data;
using AplicatieMDS.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;

namespace AplicatieMDS.Controllers
{
    [Authorize(Roles = "Admin,User,Moderator")]
    public class UsersController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UsersController(
            ApplicationDbContext context,
            UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        public IActionResult Index()
        {
            var users = from user in db.Users
                        orderby user.UserName
                        select user;

            ViewBag.UsersList = users;

            return View();
        }

        [Authorize(Roles = "User,Moderator,Admin")]
        public IActionResult Index2()
        {
            var searchTerm = HttpContext.Request.Query["searchTerm"].ToString();
            IQueryable<ApplicationUser> users = from user in db.Users
                                                orderby user.UserName
                                                select user;

            if (!string.IsNullOrEmpty(searchTerm))
            {
                users = users.Where(user => user.UserName.Contains(searchTerm));
            }

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
                ViewBag.Alert = TempData["messageType"];
            }

            int totalItems = users.Count();
            int pageSize = 3;
            var currentPage = Convert.ToInt32(HttpContext.Request.Query["page"]);
            if (currentPage == 0) currentPage = 1;
            var totalPages = (int)Math.Ceiling((double)totalItems / pageSize);
            var paginatedUsers = users.Skip((currentPage - 1) * pageSize).Take(pageSize).ToList();

            ViewBag.UsersList = paginatedUsers;
            ViewBag.CurrentPage = currentPage;
            ViewBag.TotalPages = totalPages;

            return View();
        }

        public async Task<ActionResult> Show(string id)
        {
            ApplicationUser user = await db.Users.FindAsync(id);
            var roles = await _userManager.GetRolesAsync(user);

            ViewBag.Roles = roles;

            return View(user);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            // Populate ViewBag.Roles with all available roles
            ViewBag.Roles = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            });

            return View(user);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(string id, ApplicationUser newData, [FromForm] string newRole)
        {
            ApplicationUser user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            // Update user data
            user.UserName = newData.UserName;
            user.Email = newData.Email;
            user.FirstName = newData.FirstName;
            user.LastName = newData.LastName;
            user.PhoneNumber = newData.PhoneNumber;

            // Remove all existing roles
            var currentRoles = await _userManager.GetRolesAsync(user);
            foreach (var role in currentRoles)
            {
                await _userManager.RemoveFromRoleAsync(user, role);
            }

            // Add the new role
            var roleName = await _roleManager.FindByIdAsync(newRole);
            if (roleName != null)
            {
                await _userManager.AddToRoleAsync(user, roleName.Name);
            }

            var result = await _userManager.UpdateAsync(user);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }
            foreach (var error in result.Errors)
            {
                ModelState.AddModelError(string.Empty, error.Description);
            }

            // If update fails, repopulate ViewBag.Roles and return to view
            ViewBag.Roles = _roleManager.Roles.Select(r => new SelectListItem
            {
                Text = r.Name,
                Value = r.Id
            });

            return View(user);
        }








        [HttpPost]
        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            // Remove friend invitations
            var friendInvitations = db.FriendInvitations.Where(fi => fi.ReceiverId == id || fi.SenderId == id);
            db.FriendInvitations.RemoveRange(friendInvitations);

            // Remove user friends
            var userFriends = db.UserFriends.Where(uf => uf.UserId == id || uf.FriendId == id);
            db.UserFriends.RemoveRange(userFriends);

            // Remove chat users
            var chatUsers = db.ChatUsers.Where(cu => cu.UserId == id);
            db.ChatUsers.RemoveRange(chatUsers);

            // Save changes before removing the user
            await db.SaveChangesAsync();

            // Delete user
            var result = await _userManager.DeleteAsync(user);
            if (!result.Succeeded)
            {
                // Handle error
                return BadRequest(result.Errors);
            }

            return RedirectToAction("Index");
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<ActionResult> SendInvitation(string receiverId)
        {
            var userId = _userManager.GetUserId(User);

            if (string.IsNullOrEmpty(receiverId) || userId == receiverId)
            {
                TempData["Message"] = "Invalid receiver ID or cannot invite yourself.";
                TempData["MessageType"] = "alert-danger";
                return RedirectToAction("Index2");
            }

            if (await InvitationAlreadyExists(userId, receiverId))
            {
                TempData["Message"] = "Invitation already sent.";
                TempData["MessageType"] = "alert-danger";
                return RedirectToAction("Index2");
            }

            var invitation = new FriendInvitation
            {
                SenderId = userId,
                ReceiverId = receiverId
            };
            db.FriendInvitations.Add(invitation);
            await db.SaveChangesAsync();

            TempData["Message"] = "Invitation sent successfully.";
            TempData["MessageType"] = "alert-success";
            return RedirectToAction("Index2");
        }

        private async Task<bool> InvitationAlreadyExists(string senderId, string receiverId)
        {
            return await db.FriendInvitations.AnyAsync(fi => fi.SenderId == senderId && fi.ReceiverId == receiverId);
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> ReceivedInvitations()
        {
            var userId = _userManager.GetUserId(User);
            if (string.IsNullOrEmpty(userId))
            {
                return NotFound("User not found.");
            }

            var invitations = await db.FriendInvitations
                                      .Include(fi => fi.Sender)
                                      .Where(fi => fi.ReceiverId == userId && fi.Accepted == null)
                                      .ToListAsync();

            return View(invitations);
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> AcceptInvitation(int invitationId)
        {
            var userId = _userManager.GetUserId(User);
            var invitation = await db.FriendInvitations.FindAsync(invitationId);

            if (invitation == null || invitation.ReceiverId != userId)
            {
                TempData["Message"] = "Invitation not found or you are not the receiver.";
                TempData["MessageType"] = "alert-danger";
                return RedirectToAction("ReceivedInvitations");
            }

            invitation.Accepted = true;
            db.Update(invitation);

            var userFriend = new UserFriend
            {
                UserId = userId,
                FriendId = invitation.SenderId
            };
            db.UserFriends.Add(userFriend);

            await db.SaveChangesAsync();

            TempData["Message"] = "Invitation accepted successfully.";
            TempData["MessageType"] = "alert-success";
            return RedirectToAction("Index2");
        }

        [HttpPost]
        [Authorize(Roles = "User,Moderator,Admin")]
        public async Task<IActionResult> DeclineInvitation(int invitationId)
        {
            var userId = _userManager.GetUserId(User);
            var invitation = await db.FriendInvitations.FindAsync(invitationId);

            if (invitation == null || invitation.ReceiverId != userId)
            {
                TempData["Message"] = "Invitation not found or you are not the receiver.";
                TempData["MessageType"] = "alert-danger";
                return RedirectToAction("ReceivedInvitations");
            }

            invitation.Accepted = false;
            db.Update(invitation);

AplicatieMDS/Views/Users/Edit.cshtml
@model AplicatieMDS.Models.ApplicationUser

@{
    ViewBag.Title = "Edit User";
}

<h2>Edit User</h2>

<form asp-action="Edit">
    <div class="form-group">
        <label asp-for="UserName"></label>
        <input asp-for="UserName" class="form-control" />
        <span asp-validation-for="UserName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Email"></label>
        <input asp-for="Email" class="form-control" />
        <span asp-validation-for="Email" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="PhoneNumber"></label>
        <input asp-for="PhoneNumber" class="form-control" />
        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label>Role</label>
        <select asp-for="RoleId" class="form-control" asp-items="ViewBag.Roles">
            <option value="">Select a role</option>
        </select>
    </div>
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-primary">Save</button>
</form>

AplicatieMDS/Views/Users/Index.cshtml
<br />
<br />

<div class="row">
    @foreach (var user in ViewBag.UsersList)
    {
        <div class="col-4 mb-4">
            <div class="card" style="height:100%; width: 100%;">

                <div class="card-body d-flex justify-content-between flex-column">
                    <div>
                        <p><i class="bi bi-person"> </i> UserName: @user.UserName</p>

                        <p><i class="bi bi-envelope"></i> Email utilizator: @user.Email</p>


                        @if (@user.FirstName != null)
                        {
                            <p><i class="bi bi-person"> </i> Nume utilizator: @user.FirstName</p>
                        }


                        @if (@user.LastName != null)
                        {
                            <p><i class="bi bi-person"> </i> Prenume utilizator: @user.LastName</p>
                        }


                        @if (@user.PhoneNumber != null)
                        {
                            <p><i class="bi bi-phone"></i> Telefon utilizator: @user.PhoneNumber</p>
                        }

                    </div>
                    <div class="d-flex flex-row justify-content-between p-3">


                        <a class="btn btn-success" href="/Users/Show/@user.Id">Vizualizare</a>

                        <a class="btn btn-info" href="/Users/Edit/@user.Id">Editare</a>


                        <form method="post" action="/Users/Delete/@user.Id">

                            <button class="btn btn-danger" type="submit">Stergere</button>

                        </form>

                    </div>
                </div>

            </div>
        </div>
    }

</div>

<br />
<br />

AplicatieMDS/Views/Users/Index1.cshtml
@model List<AplicatieMDS.Models.UserFriend>

@{
    Layout = "_Layout";
}

<h1>Your Friends</h1>

@if (TempData["Message"] != null)
{
    <div class="alert @TempData["MessageType"]">
        @TempData["Message"]
    </div>
}

@if (Model != null && Model.Any())
{
    <ul class="list-group">
        @foreach (var friend in Model)
        {
            <li class="list-group-item">
                Friend: @friend.Friend.UserName
                <span class="text-muted">Email: @friend.Friend.Email</span>

            </li>
        }
    </ul>
}
else
{
    <p>You have no friends added.</p>
}

AplicatieMDS/Views/Users/Index2.cshtml
<br />
<br />
@{
    string searchTerm = Context.Request.Query["searchTerm"]; // Obține searchTerm din ViewData
}
<div class="row">
    @if (TempData["Message"] != null)
    {
        <div class="alert @TempData["MessageType"]">
            @TempData["Message"]
        </div>
    }
    @foreach (var user in ViewBag.UsersList)
    {
        <div class="col-4 mb-4">
            <div class="card" style="height:100%; width: 100%;">

                <div class="card-body d-flex justify-content-between flex-column">
                    <div>
                        <p><i class="bi bi-person"> </i> UserName: @user.UserName</p>

                        <p><i class="bi bi-envelope"></i> Email utilizator: @user.Email</p>


                        @if (@user.FirstName != null)
                        {
                            <p><i class="bi bi-person"> </i> Nume utilizator: @user.FirstName</p>
                        }


                        @if (@user.LastName != null)
                        {
                            <p><i class="bi bi-person"> </i> Prenume utilizator: @user.LastName</p>
                        }


                        @if (@user.PhoneNumber != null)
                        {
                            <p><i class="bi bi-phone"></i> Telefon utilizator: @user.PhoneNumber</p>
                        }

                    </div>
                    <div class="d-flex flex-row justify-content-between p-3">

                        <!-- De facut controller pentru a trimite cerere de prietenie catre user.Id-->
                        <!-- <a class="btn btn-success" href="/Users/Show/@user.Id">Conversate</a> -->
                        <form method="post" action="/Users/SendInvitation">
                            <input type="hidden" name="receiverId" value="@user.Id" />
                            <button type="submit" class="btn btn-success">Add Friend</button>
                        </form>


                       
                    </div>
            
                </div>

            </div>
        </div>
    }

    @if (ViewBag.TotalPages > 0)
    {
        <div style="margin-top:40px;">
            <nav aria-label="Page navigation example">
                <ul class="pagination">
                    <li class="page-item">
                        <a class="page-link"
                           href="/Users/Index2?page=1@(string.IsNullOrEmpty(searchTerm) ? "" : "&searchTerm=" + searchTerm)" aria-label="Previous">
                            <span aria-hidden="true">&laquo;</span>
                        </a>
                    </li>
                    @for (int i = 1; i <= ViewBag.TotalPages; i++)
                    {
                        <li class="page-item">
                            <a class="page-link"
                               href="/Users/Index2?page=@i@(string.IsNullOrEmpty(searchTerm) ? "" : "&searchTerm=" + searchTerm)">
                                @(i)
                            </a>
                        </li>
                    }
                    <li class="page-item">
                        <a class="page-link"
                           href="/Users/Index2?page=@(ViewBag.TotalPages)@(string.IsNullOrEmpty(searchTerm) ? "" : "&searchTerm=" + searchTerm)"
                           aria-label="Next">
                            <span aria-hidden="true">&raquo;</span>
                        </a>
                    </li>
                </ul>
            </nav>
        </div>
    }

</div>

<br />
<br />

AplicatieMDS/Views/Users/ReceivedInvitations.cshtml
@model List<AplicatieMDS.Models.FriendInvitation>

@{
    Layout = "_Layout";
}

<h1>Received Invitations</h1>

@if (TempData["Message"] != null)
{
    <div class="alert @TempData["MessageType"]">
        @TempData["Message"]
    </div>
}

@if (Model != null && Model.Any())
{
    <ul class="list-group">
        @foreach (var invitation in Model)
        {
            <li class="list-group-item">
                From: @invitation.Sender.UserName
                <span class="text-muted">on @invitation.CreatedDate.ToString("dd MMM yyyy")</span>
                <div class="col-2" style="display:flex;width:170px;justify-content:space-between;margin-top:15px;">
                    <form method="post" action="/Users/AcceptInvitation">
                        <input type="hidden" name="invitationId" value="@invitation.InvitationId" />
                        <button type="submit" class="btn btn-success">Accept</button>
                    </form>
                    <form method="post"  action="/Users/DeclineInvitation">
                        <input type="hidden" name="invitationId" value="@invitation.InvitationId" />
                        <button type="submit" class="btn btn-danger">Decline</button>
                    </form>
                </div>
            </li>
        }
    </ul>
}
else
{
    <p>No invitations received.</p>
}

AplicatieMDS/Views/Users/Show.cshtml
@model AplicatieMDS.Models.ApplicationUser


<div class="card mt-3" style="height:100%; width: 100%;">

    <div class="card-body d-flex justify-content-between flex-column">
        <div>
            <p><i class="bi bi-person"> </i> UserName: @Model.UserName</p>

            <p><i class="bi bi-envelope"></i> Email utilizator: @Model.Email</p>

            @if (ViewBag.Roles.Count > 0)
            {
                <p><i class="bi bi-person"> </i> Roluri utilizator:</p>
                @foreach (var role in ViewBag.Roles)
                {
                    <span class="rounded-pill bg-dark mr-2 px-4 py-2 text-white">@role</span>
                }
            }



        </div>

        <div class="d-flex flex-row justify-content-between p-3">

            @if ((string)Model.Id != ViewBag.UserCurent)
            {
                @using (Html.BeginForm(actionName: "Delete", controllerName: "Users", method: FormMethod.Post, routeValues: new { id = @Model.Id }))
                {

                    <button class="btn btn-danger" type="submit">Sterge utilizator</button>

                }
            }
        </div>
    </div>
</div>

AplicatieMDS/Views/Users/ShowAllFriends.cshtml
@model List<AplicatieMDS.Models.UserFriend>

@{
    Layout = "_Layout";
}

<h1>Your Friends</h1>

@if (TempData["Message"] != null)
{
    <div class="alert @TempData["MessageType"]">
        @TempData["Message"]
    </div>
}

@if (Model != null && Model.Any())
{
    <ul class="list-group">
        @foreach (var friendRelation in Model)
        {
            var friend = friendRelation.UserId == ViewBag.UserCurent ? friendRelation.Friend : friendRelation.User;

            <li class="list-group-item">
                Friend: @friend.UserName
                <span class="text-muted">Email: @friend.Email</span>
                <a class="btn btn-success" href="@Url.Action("GetOrCreateChat", "Chats", new { friendId = friend.Id })">Afisare chat</a>
            </li>
        }
    </ul>
}
else
{
    <p>You have no friends added.</p>
}